package ae.mycourse.pokemon.domain

import com.google.gson.annotations.SerializedName

data class URLBaseResponse(@SerializedName(value = "ability") var ability: String,
                           @SerializedName(value = "berry") var berry: String,
                           @SerializedName(value = "berry-firmness") var berry_firmness: String,
                           @SerializedName(value = "berry-flavor") var berry_flavor: String,
                           @SerializedName(value = "characteristic") var characteristic: String,
                           @SerializedName(value = "contest-effect") var contest_effect: String,
                           @SerializedName(value = "contest-type") var contest_type: String,
                           @SerializedName(value = "egg-group") var egg_group: String,
                           @SerializedName(value = "encounter-condition") var encounter_condition: String,
                           @SerializedName(value = "encounter-condition-value") var encounter_condition_value: String,
                           @SerializedName(value = "encounter-method") var encounter_method: String,
                           @SerializedName(value = "evolution-chain") var evolution_chain: String,
                           @SerializedName(value = "evolution-trigger") var evolution_trigger: String,
                           @SerializedName(value = "gender") var gender: String,
                           @SerializedName(value = "generation") var generation: String,
                           @SerializedName(value = "growth-rate") var growth_rate: String,
                           @SerializedName(value = "item") var item: String,
                           @SerializedName(value = "item-attribute") var item_attribute: String,
                           @SerializedName(value = "item-category") var item_category: String,
                           @SerializedName(value = "item-fling-effect") var item_fling_effect: String,
                           @SerializedName(value = "item-pocket") var item_pocket: String,
                           @SerializedName(value = "language") var language: String,
                           @SerializedName(value = "location") var location: String,
                           @SerializedName(value = "location-area") var location_area: String,
                           @SerializedName(value = "machine") var machine: String,
                           @SerializedName(value = "move") var move: String,
                           @SerializedName(value = "move-ailment") var move_ailment: String,
                           @SerializedName(value = "move-battle-style") var move_battle_style: String,
                           @SerializedName(value = "move-category") var move_category: String,
                           @SerializedName(value = "move-damage-class") var move_damage_class: String,
                           @SerializedName(value = "move-learn-method") var move_learn_method: String,
                           @SerializedName(value = "move-target") var move_target: String,
                           @SerializedName(value = "nature") var nature: String,
                           @SerializedName(value = "pal-park-area") var pal_park_area: String,
                           @SerializedName(value = "pokeathlon-stat") var pokeathlon_stat: String,
                           @SerializedName(value = "pokedex") var pokedex: String,
                           @SerializedName(value = "pokemon") var pokemon: String,
                           @SerializedName(value = "pokemon-color") var pokemon_color: String,
                           @SerializedName(value = "pokemon-form") var pokemon_form: String,
                           @SerializedName(value = "pokemon-habitat") var pokemon_habitat: String,
                           @SerializedName(value = "pokemon-shape") var pokemon_shape: String,
                           @SerializedName(value = "pokemon-species") var pokemon_species: String,
                           @SerializedName(value = "region") var region: String,
                           @SerializedName(value = "stat") var stat: String,
                           @SerializedName(value = "super-contest-effect") var super_contest_effect: String,
                           @SerializedName(value = "type") var type: String,
                           @SerializedName(value = "version") var version: String,
                           @SerializedName(value = "version-group") var version_group: String,
)