package ae.mycourse.pokemon.domain

import com.google.gson.annotations.SerializedName

data class URLBaseModel( var ability: String,
                         var berry: String,
                         var berry_firmness: String,
                         var berry_flavor: String,
                         var characteristic: String,
                         var contest_effect: String,
                         var contest_type: String,
                         var egg_group: String,
                         var encounter_condition: String,
                         var encounter_condition_value: String,
                         var encounter_method: String,
                         var evolution_chain: String,
                         var evolution_trigger: String,
                         var gender: String,
                         var generation: String,
                         var growth_rate: String,
                         var item: String,
                         var item_attribute: String,
                         var item_category: String,
                         var item_fling_effect: String,
                         var item_pocket: String,
                         var language: String,
                         var location: String,
                         var location_area: String,
                         var machine: String,
                         var move: String,
                         var move_ailment: String,
                         var move_battle_style: String,
                         var move_category: String,
                         var move_damage_class: String,
                         var move_learn_method: String,
                         var move_target: String,
                         var nature: String,
                         var pal_park_area: String,
                         var pokeathlon_stat: String,
                         var pokedex: String,
                         var pokemon: String,
                         var pokemon_color: String,
                         var pokemon_form: String,
                         var pokemon_habitat: String,
                         var pokemon_shape: String,
                         var pokemon_species: String,
                         var region: String,
                         var stat: String,
                         var super_contest_effect: String,
                         var type: String,
                         var version: String,
                         var version_group: String,
)
